[workspace]
resolver = "2"
members = [
    "dioxus-demo",
    "window-ctrl",
    "custom-html",
    "rsx-demo",
    "page-design",
    "link-css",
    "page-render",
    "props-render",
    "iter-render",
    "special-attrs"
]
